title: harperdotgay
baseurl: "" 
url: "https://h4rp3r.gay"
permalink: /:categories/:title/
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  
  categories:
    enabled: false
    
  collections:
    enabled: false
    
  tags:
    enabled: true
    layouts: 
      - 'tag.html'
    title: 'Posts tagged with :tag'
    permalink: '/tag/:tag'
    slugify:
      mode: 'default'